# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Kristian/GitHub/TFE4141/project/Term_Project/Term_Project.cache/wt [current_project]
set_property parent.project_path C:/Kristian/GitHub/TFE4141/project/Term_Project/Term_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Kristian/GitHub/TFE4141/project/Term_Project/Term_Project.srcs/sources_1/imports/VHDL sources/EdgeCounter.vhd}
  {C:/Kristian/GitHub/TFE4141/project/Term_Project/Term_Project.srcs/sources_1/imports/VHDL sources/SIPO.vhd}
  {C:/Kristian/GitHub/TFE4141/project/Term_Project/VHDL sources/TopLevelStateMachine.vhd}
  C:/Kristian/GitHub/TFE4141/project/Term_Project/Term_Project.srcs/sources_1/new/RSACore.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top RSACore -part xc7z020clg484-1


write_checkpoint -force -noxdef RSACore.dcp

catch { report_utilization -file RSACore_utilization_synth.rpt -pb RSACore_utilization_synth.pb }
